image: inovex/gitlab-ci-android

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
    - when: always
    - when: never

stages:
  - build

variables:
  PROJECT_NAME: RecordEqualizer
  TELEGRAM_BOT_TOKEN: 7229201321:AAE4iukTbBGtx7GkgFGTb-FkiPTzkJjFtRo
  TELEGRAM_CHAT_ID: 981218070

assembleApplication:
  stage: build
  script:
    - ./gradlew assembleDebug
    - mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/Debug_$PROJECT_NAME.apk
  artifacts:
    name: $APPLICATION_ID
    paths:
      - app/build/outputs/apk/debug/Debug_$PROJECT_NAME.apk
  after_script:
    - |
      MESSAGE="$CI_COMMIT_MESSAGE"
      curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d "chat_id=$TELEGRAM_CHAT_ID" -d "text=$MESSAGE"

      curl -F chat_id=$TELEGRAM_CHAT_ID -F document=@app/build/outputs/apk/debug/Debug_$PROJECT_NAME.apk -F text=MESSAGE -H "Content-Type: multipart/form-data" -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument

