image: inovex/gitlab-ci-android

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
    - when: always
    - when: never

stages:
  - build

variables:
  PROJECT_NAME: RecordEqualizer

assembleApplication:
  stage: build
  script:
    - ./gradlew assembleDebug
    - mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/Debug_$PROJECT_NAME.apk
    - ./gradlew assembleRelease
    - mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/Release_$PROJECT_NAME.apk
  artifacts:
    name: $APPLICATION_ID
    paths:
      - app/build/outputs/apk/debug/Debug_$PROJECT_NAME.apk
      - app/build/outputs/apk/release/Release_$PROJECT_NAME.apk

